name: traff_app
description: "Student ERP App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  